### ISSUE TITLE
tasks.py seems to contain things that crash on windows

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#407]
running `inv setup`:
```
c:\Users\Mike\Documents\Git\collaborations\mozilla\network-pulse-api>inv setup
Copying default environment variables
Installing Python dependencies
Creating a virtualenv for this project...
Pipfile: C:\Users\Mike\Documents\Git\collaborations\mozilla\network-pulse-api\Pipfile
Using C:\Program Files\Python36\python.exe (3.6.4) to create virtualenv...
Running virtualenv with interpreter C:\Program Files\Python36\python.exe
Using base prefix 'C:\\Program Files\\Python36'
New python executable in C:\Users\Mike\.virtualenvs\network-pulse-api-meDgpO0w\Scripts\python.exe
Installing setuptools, pip, wheel...done.
Setting project for network-pulse-api-meDgpO0w to C:\Users\Mike\Documents\Git\collaborations\mozilla\network-pulse-api

Virtualenv location: C:\Users\Mike\.virtualenvs\network-pulse-api-meDgpO0w
Installing dependencies from Pipfile.lock (852e09)...
To activate this project's virtualenv, run pipenv shell.
Alternativaly, run a command inside the virtualenv with pipenv run.
Applying database migrations
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\inv.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\invoke\program.py", line 332, in run
    self.execute()
  File "c:\program files\python36\lib\site-packages\invoke\program.py", line 480, in execute
    executor.execute(*self.tasks)
  File "c:\program files\python36\lib\site-packages\invoke\executor.py", line 133, in execute
    result = call.task(*args, **call.kwargs)
  File "c:\program files\python36\lib\site-packages\invoke\tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "c:\Users\Mike\Documents\Git\collaborations\mozilla\network-pulse-api\tasks.py", line 50, in migrate
    manage(ctx, "migrate")
  File "c:\program files\python36\lib\site-packages\invoke\tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "c:\Users\Mike\Documents\Git\collaborations\mozilla\network-pulse-api\tasks.py", line 37, in manage
    **PLATFORM_ARG
TypeError: run() got multiple values for keyword argument 'env'

c:\Users\Mike\Documents\Git\collaborations\mozilla\network-pulse-api>
```

**Comment by cadecairos** [comment]
> C:\Program Files\Python36\python.exe (3.6.4)

Is this a problem in 3.6.6?

**Comment by Pomax** [comment]
always a possibility that the patch version is the problem - let me bump my version and see what happens.

**Comment by Pomax** [comment]
same problem.

**Comment by cadecairos** [comment]
@Pomax Are you still getting this error?

**Comment by Pomax** [comment]
Not tried since, let me retry.

**Comment by Pomax** [comment]
This still happens. `npm start` works, but `inv setup` crashes out.
```
c:\Users\Mike\Documents\git\collaborations\mozilla\network-pulse-api>inv setup
Copying default environment variables
Installing Python dependencies
Virtualenv already exists!
Removing existing virtualenv...
Creating a virtualenv for this project...
Pipfile: C:\Users\Mike\Documents\git\collaborations\mozilla\network-pulse-api\Pipfile
Using C:\Program Files (x86)\Python36\python.exe (3.6.6) to create virtualenv...
Running virtualenv with interpreter C:\Program Files (x86)\Python36\python.exe
Using base prefix 'C:\\Program Files (x86)\\Python36'
New python executable in C:\Users\Mike\.virtualenvs\network-pulse-api-DavATK8s\Scripts\python.exe
Installing setuptools, pip, wheel...done.
Setting project for network-pulse-api-DavATK8s to C:\Users\Mike\Documents\git\collaborations\mozilla\network-pulse-api

Virtualenv location: C:\Users\Mike\.virtualenvs\network-pulse-api-DavATK8s
Installing dependencies from Pipfile.lock (852e09)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Applying database migrations
Traceback (most recent call last):
  File "c:\program files (x86)\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python36\Scripts\inv.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python36\lib\site-packages\invoke\program.py", line 335, in run
    self.execute()
  File "c:\program files (x86)\python36\lib\site-packages\invoke\program.py", line 491, in execute
    executor.execute(*self.tasks)
  File "c:\program files (x86)\python36\lib\site-packages\invoke\executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "c:\program files (x86)\python36\lib\site-packages\invoke\tasks.py", line 128, in __call__
    result = self.body(*args, **kwargs)
  File "c:\Users\Mike\Documents\git\collaborations\mozilla\network-pulse-api\tasks.py", line 50, in migrate
    manage(ctx, "migrate")
  File "c:\program files (x86)\python36\lib\site-packages\invoke\tasks.py", line 128, in __call__
    result = self.body(*args, **kwargs)
  File "c:\Users\Mike\Documents\git\collaborations\mozilla\network-pulse-api\tasks.py", line 37, in manage
    **PLATFORM_ARG
TypeError: run() got multiple values for keyword argument 'env'
```
