### ISSUE TITLE
Running `python manage.py migrate` raises error

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#51]
Could be just me as I barely know anything about Python and Django 😬  I just did a `git pull` to update my local `master` branch, ran `python manage.py migrate`, and got a bunch of errors:

(note that `python manage.py migrate --run-syncdb` and `python manage.py makemigrations` rasied similar errors too)

```bash
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/mavisou/.virtualenvs/network-pulse-api/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/mavisou/.virtualenvs/network-pulse-api/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/mavisou/.virtualenvs/network-pulse-api/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/mavisou/.virtualenvs/network-pulse-api/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/mavisou/.virtualenvs/network-pulse-api/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/mavisou/.virtualenvs/network-pulse-api/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/mavisou/.virtualenvs/network-pulse-api/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/Users/mavisou/.virtualenvs/network-pulse-api/lib/python3.6/site-packages/django/db/migrations/loader.py", line 268, in build_graph
    raise exc
  File "/Users/mavisou/.virtualenvs/network-pulse-api/lib/python3.6/site-packages/django/db/migrations/loader.py", line 238, in build_graph
    self.graph.validate_consistency()
  File "/Users/mavisou/.virtualenvs/network-pulse-api/lib/python3.6/site-packages/django/db/migrations/graph.py", line 261, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/Users/mavisou/.virtualenvs/network-pulse-api/lib/python3.6/site-packages/django/db/migrations/graph.py", line 261, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/Users/mavisou/.virtualenvs/network-pulse-api/lib/python3.6/site-packages/django/db/migrations/graph.py", line 104, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration entries.0003_auto_20170120_2049 dependencies reference nonexistent parent node ('entries', '0002_auto_20161223_1548')
```

Can I get some help form you? @Pomax @alanmoo

**Comment by alanmoo** [comment]
Nuke your database- we squashed the migrations, so now you're off sync.

**Comment by mmmavis** [comment]
Um how? I did `python manage.py flush` and `python manage.py sqlflush` and I was still unable to resolve the errors.

**Comment by alanmoo** [comment]
`rm db.sqlite3` followed by `./manage.py migrate` should do the trick. If not, ping me in chat and we can hop on a call.

**Comment by mmmavis** [comment]
@alanmoo I tried that last night and it didn't help. Let's chat after the stand?

**Comment by Pomax** [comment]
solved during stand - migrations had to be cleared

**Comment by mmmavis** [comment]
yay colleagues' help FTW
