### ISSUE TITLE
⚠️ current master is broken ⚠️

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#615]
https://network-pulse-api-staging.herokuapp.com/api/pulse/v2/entries/ is throwing `server error 500` despite CI passing.

Server log:

```bash
2020-02-26T05:51:39.658365+00:00 app[web.1]: Internal Server Error: /api/pulse/v2/entries/
2020-02-26T05:51:39.658410+00:00 app[web.1]: Traceback (most recent call last):
2020-02-26T05:51:39.658412+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
2020-02-26T05:51:39.658412+00:00 app[web.1]:     response = get_response(request)
2020-02-26T05:51:39.658413+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
2020-02-26T05:51:39.658413+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2020-02-26T05:51:39.658414+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
2020-02-26T05:51:39.658414+00:00 app[web.1]:     response = response.render()
2020-02-26T05:51:39.658414+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/response.py", line 107, in render
2020-02-26T05:51:39.658415+00:00 app[web.1]:     self.content = self.rendered_content
2020-02-26T05:51:39.658415+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/response.py", line 72, in rendered_content
2020-02-26T05:51:39.658416+00:00 app[web.1]:     ret = renderer.render(self.data, accepted_media_type, context)
2020-02-26T05:51:39.658416+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/renderers.py", line 703, in render
2020-02-26T05:51:39.658417+00:00 app[web.1]:     context = self.get_context(data, accepted_media_type, renderer_context)
2020-02-26T05:51:39.658417+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/renderers.py", line 680, in get_context
2020-02-26T05:51:39.658417+00:00 app[web.1]:     'filter_form': self.get_filter_form(data, view, request),
2020-02-26T05:51:39.658418+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/renderers.py", line 615, in get_filter_form
2020-02-26T05:51:39.658418+00:00 app[web.1]:     html = backend().to_html(request, queryset, view)
2020-02-26T05:51:39.658419+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django_filters/rest_framework/backends.py", line 64, in to_html
2020-02-26T05:51:39.658419+00:00 app[web.1]:     template = loader.get_template(self.template)
2020-02-26T05:51:39.658420+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/template/loader.py", line 25, in get_template
2020-02-26T05:51:39.658420+00:00 app[web.1]:     raise TemplateDoesNotExist(template_name, chain=chain)
2020-02-26T05:51:39.658422+00:00 app[web.1]: django.template.exceptions.TemplateDoesNotExist: django_filters/rest_framework/form.html
```

**Comment by Pomax** [comment]
Adding `django_filters` to the list of installed apps works, but we didn't have this in our app list before and things we working fine, so I have a PR up but I'm also doing some more bisecting in case adding `django_filters` hides the actual hides rather than fixing it.
