### ISSUE TITLE
Profile list API returns status 500

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#672]
Profile list API returns status 500 if `name` is used as search param. As a result, this breaks the creator field we have on ["add new entry" form](https://www.mozillapulse.org/add) on the front end site. 
- autocomplete functionality no longer works
- `creators` added in the form can't be linked to existing users in Pulse database
- (with the current front end implementation) input like `Creator 1, Creator 2` will be treated as 1 creator named `Creator 1, Creator 2`
e.g., https://api.mozillapulse.org/api/pulse/v2/profiles/?name=mozilla

**Comment by Pomax** [comment]
Logs:
```bash
2020-07-04T17:38:31.270115+00:00 app[web.1]: Internal Server Error: /api/pulse/v2/profiles/
2020-07-04T17:38:31.270125+00:00 app[web.1]: Traceback (most recent call last):
2020-07-04T17:38:31.270126+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
2020-07-04T17:38:31.270127+00:00 app[web.1]:     response = get_response(request)
2020-07-04T17:38:31.270127+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
2020-07-04T17:38:31.270129+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2020-07-04T17:38:31.270129+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
2020-07-04T17:38:31.270130+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2020-07-04T17:38:31.270130+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2020-07-04T17:38:31.270130+00:00 app[web.1]:     return view_func(*args, **kwargs)
2020-07-04T17:38:31.270131+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
2020-07-04T17:38:31.270131+00:00 app[web.1]:     return self.dispatch(request, *args, **kwargs)
2020-07-04T17:38:31.270132+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
2020-07-04T17:38:31.270132+00:00 app[web.1]:     response = self.handle_exception(exc)
2020-07-04T17:38:31.270132+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
2020-07-04T17:38:31.270133+00:00 app[web.1]:     self.raise_uncaught_exception(exc)
2020-07-04T17:38:31.270133+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
2020-07-04T17:38:31.270134+00:00 app[web.1]:     raise exc
2020-07-04T17:38:31.270134+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
2020-07-04T17:38:31.270135+00:00 app[web.1]:     response = handler(request, *args, **kwargs)
2020-07-04T17:38:31.270135+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/generics.py", line 199, in get
2020-07-04T17:38:31.270136+00:00 app[web.1]:     return self.list(request, *args, **kwargs)
2020-07-04T17:38:31.270136+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/mixins.py", line 38, in list
2020-07-04T17:38:31.270136+00:00 app[web.1]:     queryset = self.filter_queryset(self.get_queryset())
2020-07-04T17:38:31.270137+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/generics.py", line 150, in filter_queryset
2020-07-04T17:38:31.270137+00:00 app[web.1]:     queryset = backend().filter_queryset(self.request, queryset, self)
2020-07-04T17:38:31.270138+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django_filters/rest_framework/backends.py", line 96, in filter_queryset
2020-07-04T17:38:31.270138+00:00 app[web.1]:     return filterset.qs
2020-07-04T17:38:31.270138+00:00 app[web.1]:   File "/app/pulseapi/profiles/views/profiles.py", line 182, in qs
2020-07-04T17:38:31.270139+00:00 app[web.1]:     qs = super(ProfileCustomFilter, self).qs
2020-07-04T17:38:31.270139+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django_filters/filterset.py", line 237, in qs
2020-07-04T17:38:31.270140+00:00 app[web.1]:     qs = self.filter_queryset(qs)
2020-07-04T17:38:31.270140+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django_filters/filterset.py", line 227, in filter_queryset
2020-07-04T17:38:31.270141+00:00 app[web.1]:     % (type(self).__name__, name, type(queryset).__name__)
2020-07-04T17:38:31.270141+00:00 app[web.1]: AssertionError: Expected 'ProfileCustomFilter.name' to return a QuerySet, but got a list instead.
```

**Comment by Pomax** [comment]
@benhohner old bug, but probably still worth fixing?

**Comment by benhohner** [comment]
@Pomax if it's a fairly quick fix, yep
