### ISSUE TITLE
login override looks like it has a bug

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#768]
```
2022-02-01T21:07:16.549389+00:00 app[web.1]: Internal Server Error: /accounts/google/login/callback/
2022-02-01T21:07:16.549400+00:00 app[web.1]: Traceback (most recent call last):
2022-02-01T21:07:16.549401+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
2022-02-01T21:07:16.549402+00:00 app[web.1]:     response = get_response(request)
2022-02-01T21:07:16.549402+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
2022-02-01T21:07:16.549402+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2022-02-01T21:07:16.549403+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
2022-02-01T21:07:16.549403+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2022-02-01T21:07:16.549404+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 73, in view
2022-02-01T21:07:16.549404+00:00 app[web.1]:     return self.dispatch(request, *args, **kwargs)
2022-02-01T21:07:16.549404+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 143, in dispatch
2022-02-01T21:07:16.549405+00:00 app[web.1]:     return complete_social_login(request, login)
2022-02-01T21:07:16.549405+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/allauth/socialaccount/helpers.py", line 152, in complete_social_login
2022-02-01T21:07:16.549405+00:00 app[web.1]:     return _complete_social_login(request, sociallogin)
2022-02-01T21:07:16.549406+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/allauth/socialaccount/helpers.py", line 174, in _complete_social_login
2022-02-01T21:07:16.549406+00:00 app[web.1]:     ret = _process_signup(request, sociallogin)
2022-02-01T21:07:16.549406+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/allauth/socialaccount/helpers.py", line 41, in _process_signup
2022-02-01T21:07:16.549407+00:00 app[web.1]:     sociallogin):
2022-02-01T21:07:16.549407+00:00 app[web.1]: TypeError: is_open_for_signup() takes 2 positional arguments but 3 were given
```

this is probably an passthrough invocation error in our monkey patch

Last line: https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/helpers.py#L41

**Comment by Pomax** [comment]
Note that https://github.com/mozilla/network-pulse/pull/1641 is a cosmetic PR that removes mention of "signup" from the login process.

**Comment by Pomax** [comment]
things at least don't throw 500s now, although these views are not great:

---

![image](https://user-images.githubusercontent.com/177243/153042715-2d1acee6-0002-41be-bf12-2b0b6e4f838d.png)

---

![image](https://user-images.githubusercontent.com/177243/153042673-9198b0c4-1b29-4c52-b6ca-fff19401e0de.png)

**Comment by Pomax** [comment]
https://github.com/mozilla/network-pulse-api/pull/776 to remove intermediary views

**Comment by Pomax** [comment]
This should all be fixed now.
